inevitable-dao/bento

packages/bento-web/package.json, packages/bento-web/src/dashboard/components/AddWalletModal.tsx, packages/bento-web/src/profile/components/LoginNudge.tsx
=> Implement GitHub authentication with Supabase 

packages/bento-core/src/chains/index.ts, packages/bento-core/src/tokens/index.ts, packages/bento-core/src/tokens/polygon.json, scripts/assets/polygon.ts
=> Show Polygon tokens

packages/bento-web/src/dashboard/DashboardPage.tsx, packages/bento-web/src/dashboard/utils/useNFTBalances.ts, packages/bento-web/src/dashboard/utils/useWalletBalances.ts
- @citrusinesis 잔액 가져오는 부분이 원래는 `DashboardPage` 에 로직 하나씩 하드코딩되어 있었는데, 매번 코드를 추가할 필요 없이 네트워크 타입과 Mapping 만 고치면 되게 변경하는 작업이 메인입니다. 커밋 하나씩 눌러서 변경사항 리뷰하시는 걸 추천드려요!
=> [web] Refactor balance fetching logic

packages/bento-web/src/components/Badge.tsx, packages/bento-web/src/components/PageContainer.tsx, packages/bento-web/src/dashboard/DashboardPage.tsx, packages/bento-web/src/dashboard/components/EmptyBalance.tsx, packages/bento-web/src/dashboard/components/EmptyWallet.tsx, packages/bento-web/src/pages/_app.tsx, packages/bento-web/src/profile/ProfileHomePage/ProfileHomePage.tsx, packages/bento-web/tailwind.config.js
=> [web] Initialize page content to show when no wallets are connected

packages/bento-web/src/components/AnimatedToolTip.tsx, packages/bento-web/src/dashboard/DashboardPage.tsx, packages/bento-web/src/dashboard/components/AddWalletModal.tsx, packages/bento-web/src/dashboard/sections/IntroSection.tsx
=> [web] Implement intro section content 

packages/bento-web/src/components/Checkbox.tsx, packages/bento-web/src/dashboard/DashboardPage.tsx
=> [web] Users can hide NFTs in dashboard page 

packages/bento-web/src/dashboard/DashboardPage.tsx, packages/bento-web/src/dashboard/components/TokenBalanceItem.tsx
- For better rendering
- `InlineBadge` was added in #97
=> [web] Disable `backdrop-filter` for inline badges

packages/bento-web/src/dashboard/components/TokenDetailModal.tsx
=> [web] Render NFT video if `asset.animation_url` exists

packages/bento-core/src/chains/index.ts, packages/bento-core/src/chains/interfaces.ts, packages/bento-core/src/tokens/index.ts, packages/bento-core/src/tokens/osmosis-1.json, packages/bento-web/src/pages/api/cosmos-sdk/[network]/[walletAddress].ts
- https://github.com/osmosis-labs/assetlists
- https://osmosis.stakesystems.io/swagger/#/Query/AllBalances
=> Show assets in Osmosis

packages/bento-web/src/dashboard/components/TokenDetailModal.tsx
=> Mobile responsiveness for token detail modal

packages/bento-web/src/hooks/useSession.ts
=> [web] Show OAuth error and remove query params if included

packages/bento-web/src/components/Modal.tsx, packages/bento-web/src/dashboard/components/AddWalletModal.tsx, packages/bento-web/src/dashboard/components/TokenDetailModal.tsx, packages/bento-web/src/dashboard/sections/IntroSection.tsx, packages/bento-web/src/profile/ProfileDetailPage/components/QuestionMoreModal.tsx, packages/bento-web/src/profile/ProfileHomePage/ProfileHomePage.tsx, packages/bento-web/src/profile/components/LoginNudge.tsx, packages/bento-web/src/utils/FeatureFlag.ts
=> [web] Show login dialog on `View your Dashboard` button click in dashboard

packages/bento-web/src/dashboard/utils/useWalletBalances.ts
- Related to #18 
- After #118
=> [web] Call first prices after loading

packages/bento-web/src/dashboard/components/AddWalletModal.tsx, packages/bento-web/src/dashboard/components/TokenDetailModal.tsx, packages/bento-web/src/profile/ProfileDetailPage/components/QuestionMoreModal.tsx
- `OverlayWrapper`(`Modal`) already contains `Portal`, so there's no need to be wrapped again
=> [web] Remove duplicated `Portal` wrappers

packages/bento-web/src/components/Skeleton.ts, packages/bento-web/src/dashboard/components/AssetMedia.tsx, packages/bento-web/src/dashboard/components/TokenDetailModal.tsx
=> web: Show skeleton before NFT media load

packages/bento-web/src/dashboard/DashboardPage.tsx, packages/bento-web/src/dashboard/components/TokenDetailModal.tsx
=> web: show token price/type, TVL, 24h price change and wallet allocation in `TokenDetailModal`

packages/bento-web/src/components/NavigationBar.tsx, packages/bento-web/src/dashboard/DashboardPage.tsx, packages/bento-web/src/profile/ProfileDetailPage/ProfileDetailPage.tsx, packages/bento-web/src/profile/ProfileDetailPage/components/AssetSection.tsx, packages/bento-web/src/profile/ProfileDetailPage/components/ProfileImage.tsx, packages/bento-web/src/profile/ProfileDetailPage/hooks/useProfile.ts, packages/bento-web/src/profile/components/ProfileInstance.tsx
=> web: Users can view token balances in profile

packages/bento-web/src/profile/ProfileDetailPage/components/AssetSection.tsx
=> web: remove unused imports

packages/bento-web/src/dashboard/sections/AssetRatioSection/AssetRatioSection.tsx
=> web: boolean cast condition of `assetRatioByPlatform.length`

packages/bento-web/src/profile/ProfileDetailPage/ProfileDetailPage.tsx, packages/bento-web/src/profile/ProfileDetailPage/components/AssetSection.tsx, packages/bento-web/src/profile/ProfileDetailPage/components/ProfileLinkSection.tsx, packages/bento-web/src/profile/components/ProfileInstance.tsx, packages/bento-web/src/profile/types/UserProfile.ts
=> web: add skeleton on profile page

packages/bento-web/src/profile/components/Tab.tsx
- https://odvw.slack.com/archives/C03HMSZCHB8/p1658893335712879
=> web: set max-width to tab bottom border

packages/bento-web/src/components/Portal.tsx
로그인 버튼을 눌러도 모달이 표시되지 않는 버그를 수정합니다.
=> web(dashboard): pass default id value to `Portal`

packages/bento-web/src/landing/LandingPage.tsx
- https://odvw.slack.com/archives/C03HMSZCHB8/p1659708801968019
=> web(landing): fix font-family changing bug

packages/bento-web/src/landing/sections/HeaderSection.tsx, packages/bento-web/src/utils/analytics.ts
=> web(landing): replace IR button to Twitter link

packages/bento-web/src/profile/ProfileDetailPage/components/AssetSection.tsx, packages/bento-web/src/profile/components/ProfileInstance.tsx, packages/bento-web/src/utils/FeatureFlag.ts
=> web(profile): implement NFT tab

packages/bento-web/src/components/NavigationBar.tsx, packages/bento-web/src/dashboard/components/WalletList.tsx, packages/bento-web/src/profile/components/ProfileInstance.tsx
=> web(profile): show wallets in profile

packages/bento-web/src/profile/ProfileDetailPage/components/AssetSection.tsx, packages/bento-web/src/profile/ProfileDetailPage/components/ProfileLinkSection.tsx, packages/bento-web/src/profile/ProfileDetailPage/components/ProfileViewer.tsx, packages/bento-web/src/profile/ProfileDetailPage/components/QuestionSection.tsx, packages/bento-web/src/profile/components/ProfileInstance.tsx
=> web(profile): compactor UI of `AssetSection`

packages/bento-client/src/nfts/OpenSea.ts, packages/bento-web/src/dashboard/components/TokenDetailModal.tsx, packages/bento-web/src/profile/ProfileDetailPage/components/NFTDetailModal.tsx, packages/bento-web/src/profile/ProfileDetailPage/components/NFTSection.tsx, packages/bento-web/src/profile/components/ProfileInstance.tsx, packages/bento-web/src/utils/analytics.ts
=> web(profile): users can set their NFT as a profile image

packages/bento-web/src/profile/ProfileDetailPage/ProfileDetailPage.tsx
=> web(profile): set default og image in profile detail page

packages/bento-web/src/profile/instance/sections/AssetSection.tsx
=> web(profile): update net worth view

packages/bento-web/pages/api/profile/blocks.ts, packages/bento-web/src/dashboard/sections/ProfileSummarySection.tsx
https://inevitablechanges.slack.com/archives/C03HMSZCHB8/p1664339211875579
=> [web] Retrieve social username from `user.identities` 

packages/bento-core/pricings/CoinGecko.ts
=> [core] Use edge proxy over `api.coingecko.com`

packages/bento-web/package.json, packages/bento-web/pages/api/auth/index.ts, packages/bento-web/pages/api/evm/[network]/[walletAddress].ts
- The environment variable name in Production was also wrong (`REDIS_URL` -> `NEXT_PUBLIC_REDIS_URL`)
=> [web] Bump version to 1.3.14

packages/bento-web/pages/api/auth/index.ts
=> [web] Remove `res.status` and add `withCORS` back to `/api/auth`

packages/bento-web/src/components/AnimatedTab.tsx, packages/bento-web/src/dashboard/DashboardMain.tsx, packages/bento-web/src/dashboard/components/Tab.tsx, packages/bento-web/src/dashboard/sections/NFTListSection.tsx, packages/bento-web/src/hooks/useSession.ts, packages/bento-web/src/profile/instance/ProfileInstance.tsx, packages/bento-web/src/profile/instance/sections/NFTSection.tsx, packages/bento-web/src/utils/analytics.ts
=> [web] List NFTs in dashboard main

packages/bento-web/src/dashboard/utils/useMultipleRequests.ts, packages/bento-web/src/dashboard/utils/useWalletBalances.ts
=> [web] Rewrite balance fetchers to use directly Axios instead of SWR

packages/bento-web/src/components/WalletConnector/WalletConnector.tsx, packages/bento-web/src/dashboard/DashboardMain.tsx, packages/bento-web/src/dashboard/utils/useMultipleRequests.ts, packages/bento-web/src/dashboard/utils/useNFTBalances.ts, packages/bento-web/src/dashboard/utils/useWalletBalances.ts, packages/bento-web/src/profile/instance/ProfileInstance.tsx
=> [web] Used JSON stringified keys for `useEffect` deps array

packages/bento-web/src/dashboard/utils/useDeFis.ts, packages/bento-web/src/dashboard/utils/useMultipleRequests.ts, packages/bento-web/src/dashboard/utils/useWalletBalances.ts
=> [web] Trigger force re-render on request state changes in `useMultipleRequests`

packages/bento-web/pages/_app.tsx, packages/bento-web/src/dashboard/utils/useMultipleRequests.ts, packages/bento-web/src/dashboard/utils/useNFTBalances.ts, packages/bento-web/src/dashboard/utils/useWalletBalances.ts, packages/bento-web/src/hooks/pricings.ts, packages/bento-web/src/hooks/pricings.tsx, packages/bento-web/src/hooks/useLazyEffect.ts, packages/bento-web/src/utils/debounce.ts
=> [web] Cache/Manage pricings using global context

packages/bento-web/public/locales/ko/dashboard.json, packages/bento-web/src/dashboard/DashboardMain.tsx, packages/bento-web/src/dashboard/components/DeFiStakingItem.tsx, packages/bento-web/src/dashboard/utils/useDeFis.ts, packages/bento-web/src/defi/klaytn/utils/getDeFiStakingValue.ts, packages/bento-web/src/hooks/pricings.tsx
=> [web] Show DeFi net worth by staking/location & Add Korean translations

packages/bento-api/src/defi/klaytn/klayswap/single.ts, packages/bento-api/src/defi/klaytn/kokonutswap/lp.ts, packages/bento-web/src/dashboard/components/DeFiStakingItem.tsx
=> [api, web] Show amount of correct tokens in `DeFiStakingItem`

packages/bento-api/pages/api/profile/badges/[userId].ts, packages/bento-web/src/dashboard/DashboardMain.tsx, packages/bento-web/src/dashboard/components/BadgeModal.tsx, packages/bento-web/src/dashboard/sections/BadgeListSection.tsx, packages/bento-web/src/dashboard/sections/Badges.tsx, packages/bento-web/src/utils/FeatureFlag.ts
=> [api, web] Show user badges based on cached DeFi stats

packages/bento-web/src/dashboard/DashboardMain.tsx, packages/bento-web/src/dashboard/hooks/useNFTBalances.ts
=> [web] `tokenBalances` as state & Use `flushSync` for updates

packages/bento-web/src/dashboard/DashboardMain.tsx, packages/bento-web/src/dashboard/hooks/useNFTBalances.ts
- #362 was just using `flushSync` in a wrong way
- Fixing #357. Was caused bc `ethereumPrice` is 0
=> [web] Make price updated in `useNFTBalances`

packages/bento-web/src/dashboard/sections/ProfileSummarySection.tsx
=> [web] Redirect user to their new username after updating

packages/bento-web/src/dashboard/components/TokenDetailModal.tsx, packages/bento-web/src/styles/GlobalStyle.ts
=> [web] Style token detail modal

packages/bento-common/package.json, packages/bento-common/tsconfig.json, packages/bento-core/chains/index.ts, packages/bento-core/package.json, packages/bento-core/tsconfig.json, packages/bento-web/src/profile/ProfileHomePage/components/PageViewChart.tsx
**First load JS size of `/` reduced dramatically:** `1.1 MB` -> `337 kB`
=> [core, common] Enable Tree Shaking

packages/bento-web/src/components/WalletConnector/WalletConnector.tsx, packages/bento-web/src/components/system/ActivityIndicator.tsx, packages/bento-web/src/components/system/index.ts
=> [web] Show loading while connecting wallet

packages/bento-web/src/dashboard/components/DeFiStakingItem.tsx, packages/bento-web/src/defi/klaytn/utils/getDeFiStakingValue.ts
=> [web] Show valuation and token amounts for LPs in wallet

apps/web/src/components/NavigationBar.tsx
=> [web] Remove `<a>` inside `<Link>` (Next.js 13)

apps/api/next.config.js, apps/web/next.config.js
- https://nextjs.org/blog/next-13
=> [apps] Remove `swcMinify` which is enabled by default (Next.js 13)

.github/.kodiak.toml
Using config based from https://github.com/vercel/turbo/blob/main/.github/.kodiak.toml
=> [root] Add Kodiak to automate PR updates and merges 

.github/.kodiak.toml
Follow up after #400 (After seeing the first merge commited by Kodiak in #399)
=> [root] Set Kodiak's merge commit body to `github_default`

apps/api/src/defi/osmosis/osmosis/gamm.ts
https://discord.com/channels/1025289479059157012/1034514586340171786/1037178405558435981
=> [api] Prevent double counting for unbondings in Osmosis GAMM LP pools

apps/web/src/components/system/AnimatedToolTip.tsx, apps/web/src/dashboard/sections/AssetRatioSection/AssetRatioChart.tsx, apps/web/src/dashboard/sections/AssetRatioSection/AssetRatioChartTooltip.tsx, apps/web/src/dashboard/sections/AssetRatioSection/AssetRatioSection.tsx
=> [web] Include chain for each DeFi in `AssetRatioChart`

apps/api/pages/api/protocols/[network]/[walletAddress].ts, apps/api/src/utils/filters.ts
- Reimplement #301 after #406 and #410
=> [api] Exclude empty protocol accounts

apps/web/src/dashboard/DashboardMain.tsx, apps/web/src/dashboard/DashboardMainPage.tsx, apps/web/src/dashboard/components/DetailModal.tsx, apps/web/src/dashboard/components/TokenDetailModal.tsx, apps/web/src/dashboard/components/list-items/DeFiProtocolItem.tsx, apps/web/src/dashboard/components/list-items/common/LogoWithChain.tsx, apps/web/src/dashboard/sections/NFTListSection.tsx, apps/web/src/dashboard/sections/UserProfileSection.tsx, apps/web/src/dashboard/types/TokenBalance.ts, apps/web/src/profile/instance/sections/NFTSection.tsx
=> [web] Show modal on `DeFiProtocolItem` click

apps/web/src/dashboard/sections/WalletListSection/WalletListSection.tsx
Fixes https://inevitablechanges.slack.com/archives/C045BNB6JSE/p1669264163630759
=> [web] Add more CTA cases to empty `WalletListSection`

.github/.kodiak.toml
This reverts commit 0fd39480dcf258cb504b7ca8636234323beaecf3. (#409)
=> Revert "[root] Update Kodiak config to create merge commits again (#409)

apps/web/src/components/NavigationBar.tsx
=> [web] Change `NavigationBar`'s background color to opacity black

apps/web/public/locales/en/dashboard.json, apps/web/public/locales/ko/dashboard.json, apps/web/src/dashboard/sections/NetWorthSection.tsx
=> [web] Add empty state for Portfolio Allocation
